# config/config.toml

[location]
latitude = 37.8
longitude = -77.9
elevation_m = 116

[minima]
min_altitude_deg = 20.0
min_fov_fill = 0.0
max_fov_fill = 1.0

[[optics]]
name = "Tak FS-102 + ASI533MM Pro"
telescope_aperture_mm = 102
telescope_focal_length_mm = 820
camera_sensor_width_mm = 11.31
camera_sensor_height_mm = 11.31
camera_pixel_width = 3008
camera_pixel_height = 3008
focal_reducer = 1.0

[[optics]]
name = "LX200 + ASI533MC Pro"
telescope_aperture_mm = 203
telescope_focal_length_mm = 2000
camera_sensor_width_mm = 11.3
camera_sensor_height_mm = 11.3
camera_pixel_width = 3008
camera_pixel_height = 3008
focal_reducer = 0.63
